In [1]:
import pandas as pd
import numpy as np

from Algorithm import ProvenanceSearchValues_6_20220825 as ps
from Algorithm import LatticeTraversal_2_2022405 as lt


In [23]:
healthcare = pd.read_csv("../before_selection_incomeK.csv", index_col=False)
print(len(healthcare))

887


In [4]:
healthcare.describe()

id  num-children      income  complications
count   887.000000    887.000000  887.000000     887.000000
mean    495.503946      2.390079  162.365276       5.145434
std     289.406386      1.676768  110.010853       3.129673
min       1.000000      0.000000    8.000000       0.000000
25%     243.500000      1.000000   76.000000       2.000000
50%     493.000000      2.000000  140.000000       5.000000
75%     743.000000      4.000000  218.000000       8.000000
max    1000.000000      5.000000  447.000000      10.000000

In [81]:
lst = healthcare["income"].unique()
lst.sort()
print(lst)
print(len([x for x in lst if x >= 200]))
# con = list(range(8, 448))
# print([x for x in con if x not in lst])

lst = healthcare["num-children"].unique()
lst.sort()
print(lst)

lst = healthcare["complications"].unique()
lst.sort()
print(lst)

[ 38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 106 107 108 109 110
 111 112 113 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147
 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 166
 167 168 170 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186
 187 188 189 190 191 193 195 196 197 198 199 200 201 202 203 204 205 206
 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224
 225 226 228 229 230 231 232 233 235 236 237 239 241 242 244 245 246 247
 248 249 251 254 255 257 261 263 264 266 267 268 269 271 272 273 276 282
 284 285 287 288 289 291 292 293 294 295 296 298 299 300 301 302 303 305
 308 314 317 319 320 321 322 323 324 326 327 328 32

In [11]:
children = [ 0,  1,  2,  3,  4,  5]
for i in children:
    print(len(healthcare[healthcare["num-children"] == i]))

155
157
156
149
146
124


In [12]:
complications = [ 0,  1,  2,  3,  4,  5, 6, 7, 8, 9, 10]
for i in complications:
    print(len(healthcare[healthcare["complications"] == i]))

76
68
87
80
57
93
90
81
86
96
73


In [24]:
print(len(healthcare[healthcare["income"] < 38]))

86


In [25]:
healthcare = healthcare[healthcare["income"] >= 38]
len(healthcare)

801

In [26]:
def remove_hours(hours, sam, healthcare):
    print(len(healthcare))
    a1 = healthcare[healthcare['income'] == hours].sample(sam)
    print(len(a1))
    healthcare = healthcare[~healthcare.index.isin(a1.index)]
    print(len(healthcare))
    return healthcare

healthcare = remove_hours(38, 1, healthcare)
print(len(healthcare))

801
1
800
800


In [ ]:
healthcare.to_csv("healthcare_800.csv", index=False)

In [121]:

healthcare = pd.read_csv("healthcare_800.csv", index_col=False)
print(len(healthcare))

800


In [129]:
healthcare1 = healthcare[healthcare["income"] >= 238] # size = 20
print(len(healthcare1))
healthcare2 = healthcare1[healthcare1["num-children"] <= 4] # size = 5
print(len(healthcare2))
healthcare3 = healthcare2[healthcare2["complications"] <= 8]  # size = 30
print(len(healthcare3))
healthcare4 = healthcare3[(healthcare3["county"] == "county2") | (healthcare3["county"] == "county4")]  # size = 30
print(len(healthcare4))

AA = healthcare3[healthcare3["race"] == "race2"]
print(len(AA))

183
154
76
27
18


In [128]:
lst = healthcare["income"].unique()
lst.sort()
print(lst)
print(len([x for x in lst if x >= 238]))
# con = list(range(8, 448))
# print([x for x in con if x not in lst])

lst = healthcare["num-children"].unique()
lst.sort()
print(lst)

lst = healthcare["complications"].unique()
lst.sort()
print(lst)




[ 38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 106 107 108 109 110
 111 112 113 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147
 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 166
 167 168 170 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186
 187 188 189 190 191 193 195 196 197 198 199 200 201 202 203 204 205 206
 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224
 225 226 228 229 230 231 232 233 235 236 237 239 241 242 244 245 246 247
 248 249 251 254 255 257 261 263 264 266 267 268 269 271 272 273 276 282
 284 285 287 288 289 291 292 293 294 295 296 298 299 300 301 302 303 305
 308 314 317 319 320 321 322 323 324 326 327 328 32

# make 400 k

In [133]:
healthcare = pd.read_csv("healthcare_800.csv", index_col=False)
print(len(healthcare))

800


In [134]:
print(len(healthcare[healthcare["income"] < 100]))

222


In [135]:
children = [ 0,  1,  2,  3,  4,  5]
for i in children:
    print(len(healthcare[healthcare["num-children"] == i]))

139
138
144
131
135
113


In [136]:
complications = [ 0,  1,  2,  3,  4,  5, 6, 7, 8, 9, 10]
for i in complications:
    print(len(healthcare[healthcare["complications"] == i]))

69
57
75
65
50
81
79
78
81
95
70


In [ ]:
def remove_hours(hours, sam, healthcare):
    print(len(healthcare))
    a1 = healthcare[healthcare['num-children'] == hours].sample(sam)
    print(len(a1))
    healthcare = healthcare[~healthcare.index.isin(a1.index)]
    print(len(healthcare))
    return healthcare
print(len(healthcare))
healthcare = remove_hours(5, 50, healthcare)
print(len(healthcare))
healthcare = remove_hours(4, 50, healthcare)
print(len(healthcare))
healthcare = remove_hours(3, 50, healthcare)
print(len(healthcare))
healthcare = remove_hours(2, 50, healthcare)
print(len(healthcare))
healthcare = remove_hours(1, 50, healthcare)
print(len(healthcare))
healthcare = remove_hours(0, 50, healthcare)
print(len(healthcare))

In [138]:
children = [ 0,  1,  2,  3,  4,  5]
for i in children:
    print(len(healthcare[healthcare["num-children"] == i]))



89
88
94
81
85
63


In [139]:
healthcare = remove_hours(0, 20, healthcare)
print(len(healthcare))
healthcare = remove_hours(1, 20, healthcare)
print(len(healthcare))
healthcare = remove_hours(2, 20, healthcare)
print(len(healthcare))
healthcare = remove_hours(3, 20, healthcare)
print(len(healthcare))
healthcare = remove_hours(4, 20, healthcare)
print(len(healthcare))

500
20
480
480
480
20
460
460
460
20
440
440
440
20
420
420
420
20
400
400


In [140]:
healthcare.to_csv("healthcare_400.csv", index=False)

In [143]:
lst = healthcare["income"].unique()
lst.sort()
print(lst)
print(len([x for x in lst if x >= 162]))
# con = list(range(8, 448))
# print([x for x in con if x not in lst])

lst = healthcare["num-children"].unique()
lst.sort()
print(lst)

lst = healthcare["complications"].unique()
lst.sort()
print(lst)




[ 38  40  41  42  43  44  45  46  47  48  49  50  51  52  54  55  56  57
  58  59  60  61  62  65  66  67  69  70  71  72  73  74  75  76  77  78
  79  80  82  83  84  85  86  88  91  94  95  96  98  99 100 101 102 103
 106 107 108 110 111 113 115 116 117 118 120 121 122 123 124 126 127 129
 130 131 132 133 134 135 136 137 139 140 141 142 144 145 146 147 149 150
 152 154 155 156 157 158 159 160 161 162 163 164 166 167 168 172 173 175
 177 178 179 180 181 182 183 184 185 187 188 189 190 191 193 195 196 197
 198 200 201 202 203 204 205 206 207 208 209 210 211 214 215 218 219 220
 221 222 223 224 225 226 229 231 236 242 244 245 246 248 251 255 261 264
 266 267 268 272 273 287 288 289 292 293 295 298 299 300 301 308 317 322
 323 326 327 328 330 333 338 339 343 344 345 347 350 352 353 356 357 358
 370 373 374 376 379 382 386 388 389 392 395 396 397 400 401 402 403 405
 411 413 414 417 418 420 422 427 433 436 437 442 446]
130
[0 1 2 3 4 5]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [144]:
healthcare = pd.read_csv("healthcare_400.csv", index_col=False)
healthcare1 = healthcare[healthcare["income"] >= 162] # size = 20
print(len(healthcare1))
healthcare2 = healthcare1[healthcare1["num-children"] <= 4] # size = 5
print(len(healthcare2))
healthcare3 = healthcare2[healthcare2["complications"] <= 8]  # size = 30
print(len(healthcare3))
healthcare4 = healthcare3[(healthcare3["county"] == "county2") | (healthcare3["county"] == "county4")]  # size = 30
print(len(healthcare4))

AA = healthcare3[healthcare3["race"] == "race2"]
print(len(AA))


190
163
111
39
31


# make 200 data

In [145]:
pd.read_csv("healthcare_400.csv", index_col=False)
print(len(healthcare))


400


In [146]:
lst = healthcare["income"].unique()
lst.sort()
print(lst)
print(len([x for x in lst if x >= 147]))
# con = list(range(8, 448))
# print([x for x in con if x not in lst])

lst = healthcare["num-children"].unique()
lst.sort()
print(lst)

lst = healthcare["complications"].unique()
lst.sort()
print(lst)

[ 38  40  41  42  43  44  45  46  47  48  49  50  51  52  54  55  56  57
  58  59  60  61  62  65  66  67  69  70  71  72  73  74  75  76  77  78
  79  80  82  83  84  85  86  88  91  94  95  96  98  99 100 101 102 103
 106 107 108 110 111 113 115 116 117 118 120 121 122 123 124 126 127 129
 130 131 132 133 134 135 136 137 139 140 141 142 144 145 146 147 149 150
 152 154 155 156 157 158 159 160 161 162 163 164 166 167 168 172 173 175
 177 178 179 180 181 182 183 184 185 187 188 189 190 191 193 195 196 197
 198 200 201 202 203 204 205 206 207 208 209 210 211 214 215 218 219 220
 221 222 223 224 225 226 229 231 236 242 244 245 246 248 251 255 261 264
 266 267 268 272 273 287 288 289 292 293 295 298 299 300 301 308 317 322
 323 326 327 328 330 333 338 339 343 344 345 347 350 352 353 356 357 358
 370 373 374 376 379 382 386 388 389 392 395 396 397 400 401 402 403 405
 411 413 414 417 418 420 422 427 433 436 437 442 446]
142
[0 1 2 3 4 5]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [147]:
children = [ 0,  1,  2,  3,  4,  5]
for i in children:
    print(len(healthcare[healthcare["num-children"] == i]))

69
68
74
61
65
63


In [148]:
def remove_hours(hours, sam, healthcare):
    print(len(healthcare))
    a1 = healthcare[healthcare['num-children'] == hours].sample(sam)
    print(len(a1))
    healthcare = healthcare[~healthcare.index.isin(a1.index)]
    print(len(healthcare))
    return healthcare
print(len(healthcare))
healthcare = remove_hours(5, 30, healthcare)
print(len(healthcare))
healthcare = remove_hours(4, 30, healthcare)
print(len(healthcare))
healthcare = remove_hours(3, 30, healthcare)
print(len(healthcare))
healthcare = remove_hours(2, 30, healthcare)
print(len(healthcare))
healthcare = remove_hours(1, 40, healthcare)
print(len(healthcare))
healthcare = remove_hours(0, 40, healthcare)
print(len(healthcare))


400
400
30
370
370
370
30
340
340
340
30
310
310
310
30
280
280
280
40
240
240
240
40
200
200


In [149]:
healthcare.to_csv("healthcare_200.csv", index=False)

In [155]:
lst = healthcare["income"].unique()
lst.sort()
print(lst)
print(len([x for x in lst if x >= 72]))
# con = list(range(8, 448))
# print([x for x in con if x not in lst])

lst = healthcare["num-children"].unique()
lst.sort()
print(lst)

lst = healthcare["complications"].unique()
lst.sort()
print(lst)

[ 41  43  44  46  47  48  50  51  54  57  58  59  62  65  69  71  72  74
  75  76  77  78  79  80  82  83  84  86  88  91  96  98  99 100 102 103
 107 110 111 113 115 116 117 118 120 121 122 123 124 127 129 130 131 132
 133 134 135 136 137 140 141 142 145 146 147 152 155 156 157 158 159 160
 162 164 166 172 173 177 178 180 182 183 185 187 188 189 190 197 198 201
 205 206 208 210 211 219 221 224 225 229 231 236 242 245 248 251 261 264
 266 268 272 287 289 292 293 298 299 308 327 333 338 339 347 350 353 356
 357 358 374 388 389 395 396 397 400 402 403 405 411 414 417 418 420 422
 436 437]
130
[0 1 2 3 4 5]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [157]:
healthcare = pd.read_csv("healthcare_200.csv", index_col=False)
healthcare1 = healthcare[healthcare["income"] >= 72] # size = 20
print(len(healthcare1))
healthcare2 = healthcare1[healthcare1["num-children"] <= 4] # size = 5
print(len(healthcare2))
healthcare3 = healthcare2[healthcare2["complications"] <= 8]  # size = 30
print(len(healthcare3))
healthcare4 = healthcare3[(healthcare3["county"] == "county2") | (healthcare3["county"] == "county4")]  # size = 30
print(len(healthcare4))

AA = healthcare3[healthcare3["race"] == "race2"]
print(len(AA))


179
153
120
38
32
