In [58]:
import pandas as pd
import numpy as np

from Algorithm import ProvenanceSearchValues_6_20220825 as ps
from Algorithm import LatticeTraversal_2_2022405 as lt


In [59]:
healthcare = pd.read_csv("../before_selection_incomeK.csv", index_col=False)
print(len(healthcare))

887


In [60]:
healthcare.describe()

id  num-children      income  complications
count   887.000000    887.000000  887.000000     887.000000
mean    495.503946      2.390079  162.365276       5.145434
std     289.406386      1.676768  110.010853       3.129673
min       1.000000      0.000000    8.000000       0.000000
25%     243.500000      1.000000   76.000000       2.000000
50%     493.000000      2.000000  140.000000       5.000000
75%     743.000000      4.000000  218.000000       8.000000
max    1000.000000      5.000000  447.000000      10.000000

In [7]:
lst = healthcare["income"].unique()
lst.sort()
print(lst)
print(len([x for x in lst if x >= 353]))
# con = list(range(8, 448))
# print([x for x in con if x not in lst])

lst = healthcare["num-children"].unique()
lst.sort()
print(lst)

lst = healthcare["complications"].unique()
lst.sort()
print(lst)

[  8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  25  26  27
  28  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46
  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64
  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82
  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100
 101 102 103 104 106 107 108 109 110 111 112 113 115 116 117 118 119 120
 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138
 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156
 157 158 159 160 161 162 163 164 166 167 168 170 172 173 174 175 176 177
 178 179 180 181 182 183 184 185 186 187 188 189 190 191 193 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 228 229 230 231 232 233 235
 236 237 239 241 242 244 245 246 247 248 249 251 254 255 257 261 263 264
 266 267 268 269 271 272 273 276 282 284 285 287 28

In [8]:
children = [ 0,  1,  2,  3,  4,  5]
for i in children:
    print(len(healthcare[healthcare["num-children"] == i]))

155
157
156
149
146
124


In [9]:
complications = [ 0,  1,  2,  3,  4,  5, 6, 7, 8, 9, 10]
for i in complications:
    print(len(healthcare[healthcare["complications"] == i]))

76
68
87
80
57
93
90
81
86
96
73


In [10]:
print(len(healthcare[healthcare["income"] < 38]))

86


In [11]:
healthcare = healthcare[healthcare["income"] >= 38]
len(healthcare)

801

In [12]:
def remove_hours(hours, sam, healthcare):
    print(len(healthcare))
    a1 = healthcare[healthcare['income'] == hours].sample(sam)
    print(len(a1))
    healthcare = healthcare[~healthcare.index.isin(a1.index)]
    print(len(healthcare))
    return healthcare

healthcare = remove_hours(38, 1, healthcare)
print(len(healthcare))

801
1
800
800


In [13]:
healthcare.to_csv("healthcare_800.csv", index=False)

In [63]:
healthcare = pd.read_csv("healthcare_800.csv", index_col=False)
print(len(healthcare))

healthcare1 = healthcare[healthcare["income"] >= 353] # size = 20
print(len(healthcare1))
healthcare2 = healthcare1[healthcare1["num-children"] <= 6] # size = 5
print(len(healthcare2))
healthcare3 = healthcare2[healthcare2["complications"] <= 8]  # size = 30
print(len(healthcare3))
healthcare4 = healthcare3[(healthcare3["county"] == "county2") | (healthcare3["county"] == "county4")]  # size = 30
print(len(healthcare4))

AA = healthcare4[healthcare4["race"] == "race2"]
print(len(AA))

800
80
80
45
18
6


In [20]:
lst = healthcare["income"].unique()
lst.sort()
print(lst)
print(len([x for x in lst if x >= 353]))
# con = list(range(8, 448))
# print([x for x in con if x not in lst])

lst = healthcare["num-children"].unique()
lst.sort()
print(lst)

lst = healthcare["complications"].unique()
lst.sort()
print(lst)

[ 38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 106 107 108 109 110
 111 112 113 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147
 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 166
 167 168 170 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186
 187 188 189 190 191 193 195 196 197 198 199 200 201 202 203 204 205 206
 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224
 225 226 228 229 230 231 232 233 235 236 237 239 241 242 244 245 246 247
 248 249 251 254 255 257 261 263 264 266 267 268 269 271 272 273 276 282
 284 285 287 288 289 291 292 293 294 295 296 298 299 300 301 302 303 305
 308 314 317 319 320 321 322 323 324 326 327 328 32

# make 400 k

In [21]:
healthcare = pd.read_csv("healthcare_800.csv", index_col=False)
print(len(healthcare))

800


In [22]:
print(len(healthcare[healthcare["income"] < 100]))

222


In [23]:
children = [ 0,  1,  2,  3,  4,  5]
for i in children:
    print(len(healthcare[healthcare["num-children"] == i]))

139
138
144
131
135
113


In [24]:
complications = [ 0,  1,  2,  3,  4,  5, 6, 7, 8, 9, 10]
for i in complications:
    print(len(healthcare[healthcare["complications"] == i]))

69
57
75
65
50
81
79
78
81
95
70


In [25]:
def remove_hours(hours, sam, healthcare):
    print(len(healthcare))
    a1 = healthcare[healthcare['num-children'] == hours].sample(sam)
    print(len(a1))
    healthcare = healthcare[~healthcare.index.isin(a1.index)]
    print(len(healthcare))
    return healthcare
print(len(healthcare))
healthcare = remove_hours(5, 50, healthcare)
print(len(healthcare))
healthcare = remove_hours(4, 50, healthcare)
print(len(healthcare))
healthcare = remove_hours(3, 50, healthcare)
print(len(healthcare))
healthcare = remove_hours(2, 50, healthcare)
print(len(healthcare))
healthcare = remove_hours(1, 50, healthcare)
print(len(healthcare))
healthcare = remove_hours(0, 50, healthcare)
print(len(healthcare))

800
800
50
750
750
750
50
700
700
700
50
650
650
650
50
600
600
600
50
550
550
550
50
500
500


In [26]:
children = [ 0,  1,  2,  3,  4,  5]
for i in children:
    print(len(healthcare[healthcare["num-children"] == i]))

89
88
94
81
85
63


In [27]:
healthcare = remove_hours(0, 20, healthcare)
print(len(healthcare))
healthcare = remove_hours(1, 20, healthcare)
print(len(healthcare))
healthcare = remove_hours(2, 20, healthcare)
print(len(healthcare))
healthcare = remove_hours(3, 20, healthcare)
print(len(healthcare))
healthcare = remove_hours(4, 20, healthcare)
print(len(healthcare))

500
20
480
480
480
20
460
460
460
20
440
440
440
20
420
420
420
20
400
400


In [28]:
healthcare.to_csv("healthcare_400.csv", index=False)

In [33]:
lst = healthcare["income"].unique()
lst.sort()
print(lst)
print(len([x for x in lst if x >= 292]))
# con = list(range(8, 448))
# print([x for x in con if x not in lst])

lst = healthcare["num-children"].unique()
lst.sort()
print(lst)

lst = healthcare["complications"].unique()
lst.sort()
print(lst)

[ 38  42  43  44  45  46  47  48  49  50  51  52  53  55  56  57  58  59
  60  61  62  63  64  65  66  67  68  69  70  72  74  75  76  77  78  79
  80  82  83  84  85  86  89  90  91  92  93  94  96  97  98  99 100 101
 102 103 106 107 108 109 110 111 112 113 115 120 121 122 124 125 126 127
 128 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146
 147 148 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 167
 170 172 173 175 176 177 178 179 181 182 183 185 187 188 189 190 191 193
 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 214 215 217
 218 219 220 221 222 223 224 225 228 229 230 231 232 233 235 236 237 239
 241 242 244 248 249 254 255 263 264 266 267 272 273 276 287 289 292 294
 295 298 299 300 302 305 314 317 321 322 323 324 326 328 330 338 339 344
 352 356 359 361 362 364 366 367 368 370 373 376 382 383 386 388 394 395
 396 397 399 401 402 403 405 414 417 422 423 424 427 428 432 433 434 436
 440 442 443 447]
60
[0 1 2 3 4 5]
[ 0  1  2  3  4 

In [61]:
healthcare = pd.read_csv("healthcare_400.csv", index_col=False)
healthcare1 = healthcare[healthcare["income"] >= 292] # size = 20
print(len(healthcare1))
healthcare2 = healthcare1[healthcare1["num-children"] <= 6] # size = 5
print(len(healthcare2))
healthcare3 = healthcare2[healthcare2["complications"] <= 8]  # size = 30
print(len(healthcare3))
healthcare4 = healthcare3[(healthcare3["county"] == "county2") | (healthcare3["county"] == "county4")]  # size = 30
print(len(healthcare4))

AA = healthcare3[healthcare3["race"] == "race2"]
print(len(AA))


69
69
35
14
9


# make 200 data

In [36]:
pd.read_csv("healthcare_400.csv", index_col=False)
print(len(healthcare))


400


In [41]:
lst = healthcare["income"].unique()
lst.sort()
print(lst)
print(len([x for x in lst if x >= 292]))
# con = list(range(8, 448))
# print([x for x in con if x not in lst])

lst = healthcare["num-children"].unique()
lst.sort()
print(lst)

lst = healthcare["complications"].unique()
lst.sort()
print(lst)

[ 38  42  43  44  45  46  47  48  49  50  51  52  53  55  56  57  58  59
  60  61  62  63  64  65  66  67  68  69  70  72  74  75  76  77  78  79
  80  82  83  84  85  86  89  90  91  92  93  94  96  97  98  99 100 101
 102 103 106 107 108 109 110 111 112 113 115 120 121 122 124 125 126 127
 128 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146
 147 148 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 167
 170 172 173 175 176 177 178 179 181 182 183 185 187 188 189 190 191 193
 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 214 215 217
 218 219 220 221 222 223 224 225 228 229 230 231 232 233 235 236 237 239
 241 242 244 248 249 254 255 263 264 266 267 272 273 276 287 289 292 294
 295 298 299 300 302 305 314 317 321 322 323 324 326 328 330 338 339 344
 352 356 359 361 362 364 366 367 368 370 373 376 382 383 386 388 394 395
 396 397 399 401 402 403 405 414 417 422 423 424 427 428 432 433 434 436
 440 442 443 447]
60
[0 1 2 3 4 5]
[ 0  1  2  3  4 

In [42]:
children = [ 0,  1,  2,  3,  4,  5]
for i in children:
    print(len(healthcare[healthcare["num-children"] == i]))

69
68
74
61
65
63


In [43]:
def remove_hours(hours, sam, healthcare):
    print(len(healthcare))
    a1 = healthcare[healthcare['num-children'] == hours].sample(sam)
    print(len(a1))
    healthcare = healthcare[~healthcare.index.isin(a1.index)]
    print(len(healthcare))
    return healthcare
print(len(healthcare))
healthcare = remove_hours(5, 30, healthcare)
print(len(healthcare))
healthcare = remove_hours(4, 30, healthcare)
print(len(healthcare))
healthcare = remove_hours(3, 30, healthcare)
print(len(healthcare))
healthcare = remove_hours(2, 30, healthcare)
print(len(healthcare))
healthcare = remove_hours(1, 40, healthcare)
print(len(healthcare))
healthcare = remove_hours(0, 40, healthcare)
print(len(healthcare))


400
400
30
370
370
370
30
340
340
340
30
310
310
310
30
280
280
280
40
240
240
240
40
200
200


In [44]:
healthcare.to_csv("healthcare_200.csv", index=False)

In [46]:
lst = healthcare["income"].unique()
lst.sort()
print(lst)
print(len([x for x in lst if x >= 198]))
# con = list(range(8, 448))
# print([x for x in con if x not in lst])

lst = healthcare["num-children"].unique()
lst.sort()
print(lst)

lst = healthcare["complications"].unique()
lst.sort()
print(lst)

[ 42  43  44  48  50  51  52  53  55  56  59  60  61  64  65  67  68  69
  72  75  76  78  79  80  82  83  84  85  86  90  91  96  97  99 100 101
 102 106 107 108 110 111 113 115 122 124 126 127 128 131 133 134 136 138
 140 143 145 146 148 150 151 153 155 156 157 158 159 160 161 162 163 164
 167 170 172 173 175 176 177 178 179 181 182 183 185 188 189 190 191 197
 198 206 207 215 217 218 219 220 221 222 223 224 228 229 230 231 235 236
 237 242 248 249 255 264 266 272 273 287 294 298 299 300 302 305 314 323
 324 326 328 339 352 356 359 364 366 367 368 386 394 397 402 403 405 417
 422 423 427 428 442 447]
60
[0 1 2 3 4 5]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [47]:
healthcare = pd.read_csv("healthcare_200.csv", index_col=False)
healthcare1 = healthcare[healthcare["income"] >= 198] # size = 20
print(len(healthcare1))
healthcare2 = healthcare1[healthcare1["num-children"] <= 6] # size = 5
print(len(healthcare2))
healthcare3 = healthcare2[healthcare2["complications"] <= 8]  # size = 30
print(len(healthcare3))
healthcare4 = healthcare3[(healthcare3["county"] == "county2") | (healthcare3["county"] == "county4")]  # size = 30
print(len(healthcare4))

AA = healthcare3[healthcare3["race"] == "race2"]
print(len(AA))


64
64
33
12
10


# make 100 dataset

In [48]:
pd.read_csv("healthcare_200.csv", index_col=False)
print(len(healthcare))


200


In [50]:
children = [ 0,  1,  2,  3,  4,  5]
for i in children:
    print(len(healthcare[healthcare["num-children"] == i]))

29
28
44
31
35
33


In [51]:
children = [ 0,  1,  2,  3,  4,  5]
for i in children:
    print(len(healthcare[healthcare["num-children"] == i]))

29
28
44
31
35
33


In [52]:
def remove_hours(hours, sam, healthcare):
    print(len(healthcare))
    a1 = healthcare[healthcare['num-children'] == hours].sample(sam)
    print(len(a1))
    healthcare = healthcare[~healthcare.index.isin(a1.index)]
    print(len(healthcare))
    return healthcare
print(len(healthcare))
healthcare = remove_hours(5, 15, healthcare)
print(len(healthcare))
healthcare = remove_hours(4, 15, healthcare)
print(len(healthcare))
healthcare = remove_hours(3, 15, healthcare)
print(len(healthcare))
healthcare = remove_hours(2, 25, healthcare)
print(len(healthcare))
healthcare = remove_hours(1, 15, healthcare)
print(len(healthcare))
healthcare = remove_hours(0, 15, healthcare)
print(len(healthcare))


200
200
15
185
185
185
15
170
170
170
15
155
155
155
25
130
130
130
15
115
115
115
15
100
100


In [53]:
healthcare.to_csv("healthcare_100.csv", index=False)

In [55]:
lst = healthcare["income"].unique()
lst.sort()
print(lst)
print(len([x for x in lst if x >= 108]))

lst = healthcare["num-children"].unique()
lst.sort()
print(lst)

lst = healthcare["complications"].unique()
lst.sort()
print(lst)

[ 43  44  48  50  51  55  56  59  60  64  67  69  72  75  76  79  84  86
  91  96  97 100 101 102 107 108 110 111 126 127 131 133 136 138 145 146
 148 150 157 158 159 161 162 164 167 172 173 175 176 178 185 189 190 191
 197 207 215 217 219 222 231 235 236 255 264 272 300 305 314 326 339 352
 356 359 364 366 367 386 397 402 405 417 427 428 447]
60
[0 1 2 3 4 5]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [57]:
healthcare = pd.read_csv("healthcare_100.csv", index_col=False)
print(len(healthcare))
healthcare1 = healthcare[healthcare["income"] >= 108] # size = 20
print(len(healthcare1))
healthcare2 = healthcare1[healthcare1["num-children"] <= 6] # size = 5
print(len(healthcare2))
healthcare3 = healthcare2[healthcare2["complications"] <= 8]  # size = 30
print(len(healthcare3))
healthcare4 = healthcare3[(healthcare3["county"] == "county2") | (healthcare3["county"] == "county4")]  # size = 30
print(len(healthcare4))

AA = healthcare3[healthcare3["race"] == "race2"]
print(len(AA))


100
68
68
46
9
12
