In [2]:
import pandas as pd
import numpy as np

from Algorithm import ProvenanceSearchValues_6_20220825 as ps
from Algorithm import LatticeTraversal_2_2022405 as lt


In [ ]:
adult = pd.read_csv(r"adult.data", index_col=False)

adult[:5]

In [ ]:

print(len(adult))

In [186]:

adult.describe()


age     fnlwgt  education-num  capital-gain  capital-loss  \
count 32561.00   32561.00       32561.00      32561.00      32561.00   
mean     38.58  189778.37          10.08       1077.65         87.30   
std      13.64  105549.98           2.57       7385.29        402.96   
min      17.00   12285.00           1.00          0.00          0.00   
25%      28.00  117827.00           9.00          0.00          0.00   
50%      37.00  178356.00          10.00          0.00          0.00   
75%      48.00  237051.00          12.00          0.00          0.00   
max      90.00 1484705.00          16.00      99999.00       4356.00   

       hours-per-week  
count        32561.00  
mean            40.44  
std             12.35  
min              1.00  
25%             40.00  
50%             40.00  
75%             45.00  
max             99.00

In [187]:
lst = adult["hours-per-week"].unique()
lst.sort()
print(lst)
lst2 = list(range(1, 100))
print([x for x in lst2 if x not in lst])
# without 69, 71


lst = adult["education-num"].unique()
lst.sort()
print(lst)

lst = adult["capital-gain"].unique()
lst.sort()
print(lst)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 70 72 73 74
 75 76 77 78 80 81 82 84 85 86 87 88 89 90 91 92 94 95 96 97 98 99]
[69, 71, 79, 83, 93]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[    0   114   401   594   914   991  1055  1086  1111  1151  1173  1409
  1424  1455  1471  1506  1639  1797  1831  1848  2009  2036  2050  2062
  2105  2174  2176  2202  2228  2290  2329  2346  2354  2387  2407  2414
  2463  2538  2580  2597  2635  2653  2829  2885  2907  2936  2961  2964
  2977  2993  3103  3137  3273  3325  3411  3418  3432  3456  3464  3471
  3674  3781  3818  3887  3908  3942  4064  4101  4386  4416  4508  4650
  4687  4787  4865  4931  4934  5013  5060  5178  5455  5556  5721  6097
  6360  6418  6497  6514  6723  6767  6849  7298  7430  7443  7688  7896
  7978  8614  9386  9562 10520 10566 10605 11678 13550 140

In [188]:
def remove_hours(hours, sam, adult):
    print(len(adult))
    a1 = adult[adult['hours-per-week'] == hours].sample(sam)
    print(len(a1))
    adult = adult[~adult.index.isin(a1.index)]
    print(len(adult))
    return adult



In [189]:
print(len(adult[adult['hours-per-week'] == 20]))
print(len(adult[adult['hours-per-week'] == 30]))
print(len(adult[adult['hours-per-week'] == 35]))
print(len(adult[adult['hours-per-week'] == 40]))
print(len(adult[adult['hours-per-week'] == 45]))
print(len(adult[adult['hours-per-week'] == 50]))
print(len(adult[adult['hours-per-week'] == 60]))

print(len(adult[adult['hours-per-week'] == 15]))
print(len(adult[adult['hours-per-week'] == 25]))
print(len(adult[adult['hours-per-week'] == 36]))
print(len(adult[adult['hours-per-week'] == 38]))
print(len(adult[adult['hours-per-week'] == 48]))
print(len(adult[adult['hours-per-week'] == 55]))



1224
1149
1297
15217
1824
2819
1475
404
674
220
476
517
694


In [190]:
adult = remove_hours(20, 100, adult)
adult = remove_hours(30, 100, adult)
adult = remove_hours(35, 100, adult)
adult = remove_hours(40, 161, adult)
adult = remove_hours(45, 100, adult)



32561
100
32461
32461
100
32361
32361
100
32261
32261
161
32100
32100
100
32000
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 70 72 73 74
 75 76 77 78 80 81 82 84 85 86 87 88 89 90 91 92 94 95 96 97 98 99]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [192]:
lst = adult["hours-per-week"].unique()
lst.sort()
print(lst)
# [69, 71, 79, 83, 93]
lst = adult["education-num"].unique()
lst.sort()
print(lst)


lst = adult["capital-gain"].unique()
lst.sort()
print(lst)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 70 72 73 74
 75 76 77 78 80 81 82 84 85 86 87 88 89 90 91 92 94 95 96 97 98 99]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[    0   114   401   594   914   991  1055  1086  1111  1151  1173  1409
  1424  1455  1471  1506  1797  1831  1848  2009  2036  2050  2062  2105
  2174  2176  2202  2228  2290  2329  2346  2354  2387  2407  2414  2463
  2538  2580  2597  2635  2653  2829  2885  2907  2936  2961  2964  2977
  2993  3103  3137  3273  3325  3411  3418  3432  3456  3464  3471  3674
  3781  3818  3887  3908  3942  4064  4101  4386  4416  4508  4650  4687
  4787  4865  4931  4934  5013  5060  5178  5455  5556  5721  6097  6360
  6418  6497  6514  6723  6767  6849  7298  7430  7443  7688  7896  7978
  8614  9386  9562 10520 10566 10605 11678 13550 14084 14344 15020 15024
 15831

In [191]:

adult.to_csv("adult_32k.csv", index=False)


# query scale


In [1]:

# 32k data
adult = pd.read_csv(r"adult_32k.csv", index_col=False)
print(len(adult))
adult1 = adult[adult["hours-per-week"] >= 20] # size = 20
print(len(adult1))
adult2 = adult1[adult1["education-num"] >= 5] # size = 5
print(len(adult2))
adult3 = adult2[adult2["capital-gain"] >= 2329]  # size = 30
print(len(adult3))


female = adult3[adult3["sex"]=="Female"]
print(len(female))

NameError: name 'pd' is not defined

In [260]:


data_file = r"adult_32k.csv"
query_file = r"query1.json"
constraint_file = r"constraint1.json"
time_limit = 5 * 60

print("========================== provenance search ===================================")
minimal_refinements1, running_time1, assign_num = \
    ps.FindMinimalRefinement(data_file, query_file, constraint_file, time_limit)

print("running time = {}".format(running_time1))
print(*minimal_refinements1, sep="\n")

# print("========================== lattice traversal ===================================")
#
# minimal_refinements2, minimal_added_refinements2, running_time2 = \
#     lt.FindMinimalRefinement(data_file, query_file, constraint_file, time_limit)
# print("running time = {}".format(running_time2))
# if running_time2 < time_limit:
#     print(*minimal_refinements2, sep="\n")

========================== provenance search ===================================
selected_attributes ['education-num', 'hours-per-week', 'capital-gain']
prepare time = 0.0007250308990478516
time of test_satisfying_rows = 1.3828277587890625e-05
time of get_provenance_relax_only = 2.400442123413086
len(data) not satisfying = 2863
possible_value_table:
     education-num  hours-per-week  capital-gain
0            5.00           20.00          2329
1            4.00           19.00          2290
2            3.00           18.00          2228
3            2.00           17.00          2202
4            1.00           16.00          2176
5             NaN           15.00          2174
6             NaN           14.00          2105
7             NaN           13.00          2062
8             NaN           12.00          2050
9             NaN           11.00          2036
10            NaN           10.00          2009
11            NaN            9.00          1848
12            NaN      


# make a 16k data


In [246]:
adult = pd.read_csv("adult_32k.csv", index_col=False)
print(len(adult))


print(len(adult[adult['hours-per-week'] >= 41]))
print(len(adult[adult['hours-per-week'] == 40]))


32000
9481
15056


In [247]:

adult = adult[adult["hours-per-week"] <= 40]


In [248]:
print(len(adult))
adult = remove_hours(40, 6519, adult)
print(len(adult))


22519
22519
6519
16000
16000


In [249]:
adult.to_csv("adult_16k.csv",index=False)

In [250]:
lst = adult["hours-per-week"].unique()
lst.sort()
print(lst)
# [69, 71, 79, 83, 93]
lst = adult["education-num"].unique()
lst.sort()
print(lst)


lst = adult["capital-gain"].unique()
lst.sort()
print(lst)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[    0   114   401   594   914   991  1055  1086  1111  1151  1173  1409
  1424  1455  1471  1506  1797  1831  1848  2009  2036  2050  2062  2105
  2174  2176  2202  2228  2290  2329  2346  2354  2387  2407  2414  2463
  2580  2597  2635  2653  2829  2885  2907  2936  2961  2964  2977  2993
  3103  3137  3273  3325  3411  3418  3432  3456  3464  3471  3674  3781
  3818  3887  3908  3942  4064  4101  4386  4416  4508  4650  4687  4787
  4865  4931  4934  5013  5060  5178  5455  5556  5721  6097  6360  6418
  6497  6514  6723  6767  6849  7298  7430  7443  7688  7978  8614  9386
 10520 10566 10605 13550 14084 14344 15020 15024 15831 18481 20051 22040
 25124 25236 27828 34095 41310 99999]


In [4]:

# 16k data
adult = pd.read_csv(r"adult_16k.csv", index_col=False)
print(len(adult))
adult1 = adult[adult["hours-per-week"] >= 20] # size = 20
print(len(adult1))
adult2 = adult1[adult1["education-num"] >= 5] # size = 5
print(len(adult2))
adult3 = adult2[adult2["capital-gain"] >= 2329]  # size = 30
print(len(adult3))

female = adult3[adult3["sex"]=="Female"]
print(len(female))

16000
14296
13689
791
235


In [261]:

data_file = r"adult_16k.csv"
query_file = r"query2.json"
constraint_file = r"constraint2.json"
time_limit = 5 * 60

print("========================== provenance search ===================================")
minimal_refinements1, running_time1, assign_num = \
    ps.FindMinimalRefinement(data_file, query_file, constraint_file, time_limit)

print("running time = {}".format(running_time1))
print(*minimal_refinements1, sep="\n")


========================== provenance search ===================================
selected_attributes ['education-num', 'hours-per-week', 'capital-gain']
prepare time = 0.0023288726806640625
time of test_satisfying_rows = 2.1457672119140625e-06
time of get_provenance_relax_only = 1.1472177505493164
len(data) not satisfying = 1456
possible_value_table:
     education-num  hours-per-week  capital-gain
0            5.00           20.00          2329
1            4.00           19.00          2290
2            3.00           18.00          2228
3            2.00           17.00          2202
4            1.00           16.00          2176
5             NaN           15.00          2174
6             NaN           14.00          2105
7             NaN           13.00          2062
8             NaN           12.00          2050
9             NaN           11.00          2036
10            NaN           10.00          2009
11            NaN            9.00          1848
12            NaN     


# 8k data


In [233]:
adult = pd.read_csv("adult_16k.csv", index_col=False)
print(len(adult))


print(len(adult[adult['hours-per-week'] >= 41]))
print(len(adult[adult['hours-per-week'] == 40]))


16000
0
8537


In [234]:
print(len(adult[adult['hours-per-week'] == 30]))
print(len(adult[adult['hours-per-week'] == 35]))
print(len(adult[adult['hours-per-week'] == 40]))

print(len(adult[adult['hours-per-week'] == 15]))
print(len(adult[adult['hours-per-week'] == 25]))
print(len(adult[adult['hours-per-week'] == 36]))
print(len(adult[adult['hours-per-week'] == 38]))

1049
1197
8537
404
674
220
476


In [235]:
print(len(adult))
adult = remove_hours(40, 7000, adult)
print(len(adult))
adult = remove_hours(30, 500, adult)
print(len(adult))
adult = remove_hours(35, 500, adult)
print(len(adult))

16000
16000
7000
9000
9000
9000
500
8500
8500
8500
500
8000
8000


In [236]:
adult.to_csv("adult_8k.csv", index=False)

In [237]:
lst = adult["hours-per-week"].unique()
lst.sort()
print(lst)
# [69, 71, 79, 83, 93]
lst = adult["education-num"].unique()
lst.sort()
print(lst)


lst = adult["capital-gain"].unique()
lst.sort()
print(lst)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[    0   114   401   594   914   991  1055  1086  1111  1151  1409  1424
  1455  1471  1506  1797  1831  1848  2036  2050  2062  2105  2174  2176
  2202  2228  2290  2329  2346  2354  2414  2463  2580  2597  2635  2653
  2829  2885  2907  2936  2961  2964  2977  2993  3103  3137  3273  3325
  3411  3418  3432  3456  3464  3471  3674  3781  3818  3887  3908  3942
  4064  4101  4386  4416  4508  4650  4787  4865  4931  4934  5013  5178
  5455  5556  6360  6418  6497  6514  6723  6767  6849  7298  7430  7443
  7688  8614  9386 10520 10566 10605 13550 14084 15024 15831 18481 20051
 22040 25124 25236 27828 34095 41310 99999]


In [253]:

# 8k data
adult = pd.read_csv(r"adult_8k.csv", index_col=False)
print(len(adult))
adult1 = adult[adult["hours-per-week"] >= 20] # size = 20
print(len(adult1))
adult2 = adult1[adult1["education-num"] >= 5] # size = 5
print(len(adult2))
adult3 = adult2[adult2["capital-gain"] >= 2354]  # size = 30
print(len(adult3))

female = adult3[adult["sex"]=="Female"]
print(len(female))


8000
6296
6033
299
120


/var/folders/y1/vnpd8xm133v6hdbz8zf5wzsc0000gn/T/ipykernel_65792/3714373379.py:11: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  female = adult3[adult["sex"]=="Female"]


In [262]:

data_file = r"adult_8k.csv"
query_file = r"query3.json"
constraint_file = r"constraint3.json"
time_limit = 5 * 60

print("========================== provenance search ===================================")
minimal_refinements1, running_time1, assign_num = \
    ps.FindMinimalRefinement(data_file, query_file, constraint_file, time_limit)

print("running time = {}".format(running_time1))
print(*minimal_refinements1, sep="\n")



========================== provenance search ===================================
selected_attributes ['education-num', 'hours-per-week', 'capital-gain']
prepare time = 0.0007760524749755859
time of test_satisfying_rows = 0.0
time of get_provenance_relax_only = 0.8993031978607178
len(data) not satisfying = 1161
possible_value_table:
     education-num  hours-per-week  capital-gain
0            5.00           20.00          2354
1            4.00           19.00          2346
2            3.00           18.00          2329
3            2.00           17.00          2290
4            1.00           16.00          2228
5             NaN           15.00          2202
6             NaN           14.00          2176
7             NaN           13.00          2174
8             NaN           12.00          2105
9             NaN           11.00          2062
10            NaN           10.00          2050
11            NaN            9.00          2036
12            NaN            8.00        


# 4k data


In [263]:
adult = pd.read_csv("adult_8k.csv", index_col=False)
print(len(adult))


print(len(adult[adult['hours-per-week'] >= 41]))
print(len(adult[adult['hours-per-week'] == 40]))


8000
0
1537


In [265]:
print(len(adult[adult['hours-per-week'] == 30]))
print(len(adult[adult['hours-per-week'] == 35]))

print(len(adult[adult['hours-per-week'] == 15]))
print(len(adult[adult['hours-per-week'] == 25]))
print(len(adult[adult['hours-per-week'] == 36]))
print(len(adult[adult['hours-per-week'] == 38]))

549
697
404
674
220
476


In [266]:
print(len(adult))
adult = remove_hours(40, 1000, adult)
print(len(adult))
adult = remove_hours(35, 500, adult)
print(len(adult))
adult = remove_hours(25, 500, adult)
print(len(adult))

8000
8000
1000
7000
7000
7000
500
6500
6500
6500
500
6000
6000


In [268]:
print(len(adult[adult['hours-per-week'] == 30]))
print(len(adult[adult['hours-per-week'] == 15]))
print(len(adult[adult['hours-per-week'] == 38]))

print(len(adult[adult['hours-per-week'] == 35]))
print(len(adult[adult['hours-per-week'] == 25]))
print(len(adult[adult['hours-per-week'] == 36]))


549
404
476
197
174
220


In [269]:
print(len(adult))
adult = remove_hours(30, 400, adult)
print(len(adult))
adult = remove_hours(15, 300, adult)
print(len(adult))
adult = remove_hours(38, 300, adult)
print(len(adult))

6000
6000
400
5600
5600
5600
300
5300
5300
5300
300
5000
5000


In [272]:
print(len(adult[adult['hours-per-week'] == 30]))
print(len(adult[adult['hours-per-week'] == 15]))
print(len(adult[adult['hours-per-week'] == 38]))

print(len(adult[adult['hours-per-week'] == 35]))
print(len(adult[adult['hours-per-week'] == 25]))
print(len(adult[adult['hours-per-week'] == 36]))

for i in range(1, 40):
    if len(adult[adult['hours-per-week'] == i]) > 100:
        print(i, len(adult[adult['hours-per-week'] == i]))

print(len(adult[adult['hours-per-week'] == 20]))


149
104
176
197
174
220
8 145
10 278
12 173
15 104
16 205
20 1124
24 252
25 174
30 149
32 266
35 197
36 220
37 149
38 176
1124


In [273]:
print(len(adult))
adult = remove_hours(20, 1000, adult)
print(len(adult))

5000
5000
1000
4000
4000


In [274]:
adult.to_csv("adult_4k.csv", index=False)

In [296]:
lst = adult["hours-per-week"].unique()
lst.sort()
print(lst)
# [69, 71, 79, 83, 93]
lst = adult["education-num"].unique()
lst.sort()
print(lst)


lst = adult["capital-gain"].unique()
lst.sort()
print(lst)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[    0   401   594   991  1055  1409  1424  1455  1797  1848  2062  2176
  2202  2228  2329  2354  2414  2597  2635  2653  2829  2936  2964  3137
  3325  3411  3418  3456  3464  3781  3818  3908  4064  4101  4386  4650
  4931  5013  5178  5556  6418  6497  6514  6723  6767  7298  7688  9386
 10520 10605 13550 15024 15831 18481 20051 34095 99999]


In [277]:

# 8k data
adult = pd.read_csv(r"adult_4k.csv", index_col=False)
print(len(adult))
adult1 = adult[adult["hours-per-week"] >= 20] # size = 20
print(len(adult1))
adult2 = adult1[adult1["education-num"] >= 5] # size = 5
print(len(adult2))
adult3 = adult2[adult2["capital-gain"] >= 2936]  # size = 30
print(len(adult3))

female = adult3[adult["sex"]=="Female"]
print(len(female))


4000
2596
2478
124
60


/var/folders/y1/vnpd8xm133v6hdbz8zf5wzsc0000gn/T/ipykernel_65792/3130577479.py:11: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  female = adult3[adult["sex"]=="Female"]


In [278]:

data_file = r"adult_4k.csv"
query_file = r"query4.json"
constraint_file = r"constraint4.json"
time_limit = 5 * 60

print("========================== provenance search ===================================")
minimal_refinements1, running_time1, assign_num = \
    ps.FindMinimalRefinement(data_file, query_file, constraint_file, time_limit)

print("running time = {}".format(running_time1))
print(*minimal_refinements1, sep="\n")



========================== provenance search ===================================
selected_attributes ['education-num', 'hours-per-week', 'capital-gain']
prepare time = 0.0015909671783447266
time of test_satisfying_rows = 0.0005481243133544922
time of get_provenance_relax_only = 0.5401690006256104
len(data) not satisfying = 924
possible_value_table:
     education-num  hours-per-week  capital-gain
0            5.00           20.00          2936
1            4.00           19.00          2885
2            3.00           18.00          2829
3            2.00           17.00          2653
4            1.00           16.00          2635
5             NaN           15.00          2597
6             NaN           14.00          2463
7             NaN           13.00          2414
8             NaN           12.00          2354
9             NaN           11.00          2329
10            NaN           10.00          2290
11            NaN            9.00          2228
12            NaN       


# 2k data

In [282]:
adult = pd.read_csv("adult_4k.csv", index_col=False)
print(len(adult))

for i in range(1, 40):
    if len(adult[adult['hours-per-week'] == i]) > 200:
        print(i, len(adult[adult['hours-per-week'] == i]))
        print(len(adult))
        adult = remove_hours(i, 150, adult)
        print(len(adult))


4000
10 278
4000
4000
150
3850
3850
16 205
3850
3850
150
3700
3700
24 252
3700
3700
150
3550
3550
32 266
3550
3550
150
3400
3400
36 220
3400
3400
150
3250
3250


In [285]:
for i in range(1, 40):
    if len(adult[adult['hours-per-week'] == i]) > 150:
        print(i, len(adult[adult['hours-per-week'] == i]))
        print(len(adult))
        adult = remove_hours(i, 100, adult)
        print(len(adult))

12 173
3250
3250
100
3150
3150
25 174
3150
3150
100
3050
3050
35 197
3050
3050
100
2950
2950
38 176
2950
2950
100
2850
2850


In [291]:
print(len(adult[adult["hours-per-week"] == 40]))
print(len(adult[adult["hours-per-week"] == 39]))
print(len(adult[adult["hours-per-week"] == 38]))
print(len(adult[adult["hours-per-week"] == 37]))
adult = adult[adult["hours-per-week"] < 37]
print(len(adult))

537
38
76
149
2050


In [294]:
print(len(adult[adult["hours-per-week"] == 36]))
adult = remove_hours(36, 50, adult)
print(len(adult))


70
2050
50
2000
2000


In [295]:

adult.to_csv("adult_2k.csv", index=False)


In [297]:

lst = adult["hours-per-week"].unique()
lst.sort()
print(lst)
# [69, 71, 79, 83, 93]
lst = adult["education-num"].unique()
lst.sort()
print(lst)


lst = adult["capital-gain"].unique()
lst.sort()
print(lst)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[    0   401   594   991  1055  1409  1424  1455  1797  1848  2062  2176
  2202  2228  2329  2354  2414  2597  2635  2653  2829  2936  2964  3137
  3325  3411  3418  3456  3464  3781  3818  3908  4064  4101  4386  4650
  4931  5013  5178  5556  6418  6497  6514  6723  6767  7298  7688  9386
 10520 10605 13550 15024 15831 18481 20051 34095 99999]


In [298]:

# 8k data
adult = pd.read_csv(r"adult_2k.csv", index_col=False)
print(len(adult))
adult1 = adult[adult["hours-per-week"] >= 20] # size = 20
print(len(adult1))
adult2 = adult1[adult1["education-num"] >= 5] # size = 5
print(len(adult2))
adult3 = adult2[adult2["capital-gain"] >= 3781]  # size = 30
print(len(adult3))

female = adult3[adult["sex"]=="Female"]
print(len(female))


2000
996
963
34
23


/var/folders/y1/vnpd8xm133v6hdbz8zf5wzsc0000gn/T/ipykernel_65792/3615218563.py:11: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  female = adult3[adult["sex"]=="Female"]


In [299]:

data_file = r"adult_2k.csv"
query_file = r"query5.json"
constraint_file = r"constraint5.json"
time_limit = 5 * 60

print("========================== provenance search ===================================")
minimal_refinements1, running_time1, assign_num = \
    ps.FindMinimalRefinement(data_file, query_file, constraint_file, time_limit)

print("running time = {}".format(running_time1))
print(*minimal_refinements1, sep="\n")



========================== provenance search ===================================
selected_attributes ['education-num', 'hours-per-week', 'capital-gain']
prepare time = 0.0012619495391845703
time of test_satisfying_rows = 2.1457672119140625e-06
time of get_provenance_relax_only = 0.3677091598510742
len(data) not satisfying = 645
possible_value_table:
     education-num  hours-per-week  capital-gain
0            5.00           20.00          3781
1            4.00           19.00          3464
2            3.00           18.00          3456
3            2.00           17.00          3418
4            1.00           16.00          3411
5             NaN           15.00          3325
6             NaN           14.00          3137
7             NaN           13.00          2964
8             NaN           12.00          2936
9             NaN           11.00          2829
10            NaN           10.00          2653
11            NaN            9.00          2635
12            NaN      

# 1k data

In [309]:
adult = pd.read_csv("adult_2k.csv", index_col=False)
print(len(adult))

print(len(adult[adult["hours-per-week"] >= 23]))


2000
804


In [310]:

for i in range(1, 40):
    if len(adult[adult['hours-per-week'] == i]) > 100:
        print(i, len(adult[adult['hours-per-week'] == i]))
        # print(len(adult))
        # adult = remove_hours(i, 150, adult)
        # print(len(adult))


8 145
10 128
15 104
20 124
24 102
30 149
32 116


In [311]:
adult = adult[adult["hours-per-week"] <= 22]
print(len(adult))

1196


In [312]:
adult = remove_hours(8, 50, adult)
print(len(adult))
adult = remove_hours(10, 50, adult)
print(len(adult))
adult = remove_hours(15, 50, adult)
print(len(adult))
adult = remove_hours(20, 46, adult)
print(len(adult))

1196
50
1146
1146
1146
50
1096
1096
1096
50
1046
1046
1046
46
1000
1000


In [313]:
adult.to_csv("adult_1k.csv", index=False)

In [314]:

lst = adult["hours-per-week"].unique()
lst.sort()
print(lst)
# [69, 71, 79, 83, 93]
lst = adult["education-num"].unique()
lst.sort()
print(lst)

lst = adult["capital-gain"].unique()
lst.sort()
print(lst)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[    0   401   594   991  1055  1409  1424  1455  1797  1848  2062  2176
  2202  2329  2354  2414  2635  2653  2829  2964  3325  3456  3781  3818
  4064  4386  4650  4931  6418  6514  6767  7298  7688  9386 10605 15024
 15831 18481 20051 34095]


In [315]:
# 8k data
adult = pd.read_csv(r"adult_1k.csv", index_col=False)
print(len(adult))
adult1 = adult[adult["hours-per-week"] >= 20] # size = 20
print(len(adult1))
adult2 = adult1[adult1["education-num"] >= 6] # size = 5
print(len(adult2))
adult3 = adult2[adult2["capital-gain"] >= 6514]  # size = 30
print(len(adult3))

female = adult3[adult["sex"]=="Female"]
print(len(female))


1000
146
136
2
2


/var/folders/y1/vnpd8xm133v6hdbz8zf5wzsc0000gn/T/ipykernel_65792/540706054.py:11: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  female = adult3[adult["sex"]=="Female"]


In [316]:

data_file = r"adult_1k.csv"
query_file = r"query6.json"
constraint_file = r"constraint6.json"
time_limit = 5 * 60

print("========================== provenance search ===================================")
minimal_refinements1, running_time1, assign_num = \
    ps.FindMinimalRefinement(data_file, query_file, constraint_file, time_limit)

print("running time = {}".format(running_time1))
print(*minimal_refinements1, sep="\n")



========================== provenance search ===================================
selected_attributes ['education-num', 'hours-per-week', 'capital-gain']
prepare time = 0.0008800029754638672
time of test_satisfying_rows = 9.5367431640625e-07
time of get_provenance_relax_only = 0.2174673080444336
len(data) not satisfying = 381
possible_value_table:
     education-num  hours-per-week  capital-gain
0            6.00           20.00          6514
1            5.00           19.00          6418
2            4.00           18.00          4931
3            3.00           17.00          4650
4            2.00           16.00          4386
5             NaN           15.00          4064
6             NaN           14.00          3818
7             NaN           13.00          3781
8             NaN           12.00          3456
9             NaN           11.00          3325
10            NaN           10.00          2964
11            NaN            9.00          2829
12            NaN         